amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    scan_topic: "/scan"
    laser_min_range: 0.0
    laser_max_range: 15.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    enable_groot_monitoring: False

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_plugins: ["FollowPath"]

planner_server:
  ros__parameters:
    use_sim_time: True
    planner_plugins: ["GridBased"]

recovery_server:
  ros__parameters:
    use_sim_time: True

slam_toolbox:
  ros__parameters:
    use_sim_time: True
    mode: "mapping"
    max_laser_range: 15.0

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    robot_radius: 0.2
    rolling_window: true
    width: 3.0
    height: 3.0

global_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    resolution: 0.05
    robot_radius: 0.2
    width: 10.0
    height: 10.0

